version: '3.8'

services:
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    image: myapp-server
    container_name: myapp-node-server
    command: npm start
    volumes:
      - ./Server/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    env_file: ./Server/.env
    environment:
      - NODE_ENV=development
    
  mongo:
    image: mongo
    volumes:
      - data-volume:/data/db
    ports:
      - "27017:27017"
    
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: myapp-client
    container_name: myapp-react-client
    command: npm start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    


volumes:
    data-volume:
    node_modules:
    web-root:
      driver: local